# Generated by Django 3.0.7 on 2021-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0003_auto_20210611_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image'),
        ),
    ]
