# Generated by Django 3.0.7 on 2021-06-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0005_auto_20210612_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
